name: Deploy to AWS lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: yarn install

      - name: Test
        run: yarn test

      - name: Setup AWS secrets
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key_id
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_access_key
          echo ${{ secrets.AWS_REGION }} > aws_region

      - name: Update AWS Lambda function code
        run: |
          export AWS_ACCESS_KEY_ID=$(cat aws_access_key_id)
          export AWS_SECRET_ACCESS_KEY=$(cat aws_secret_access_key)
          export AWS_REGION=$(cat aws_region)
          yarn compile
          aws lambda update-function-code --function-name iosShortcutsResponder --region $AWS_REGION --zip-file fileb://functions.zip
